# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

NSJAIL_DEBS = struct(
    revision = "1578324891",
    sha256 = "caa31859d3520ad82749fa539c01553c5829527829b0c2d3a652db9aa8057d57",
)

RBE_IMAGE_DEBS = struct(
    revision = "1572370336",
    sha256 = "d1b38af6de19745750b45de1dcd09aba7912a52db5d5b40b286a8c88dd46617e",
)

GOOGLE_NSJAIL = struct(
    commit = "04e5fae0e3e0efd3e68a11e2d5b5e3e1a42811ac",
    sha256 = "c62eb79371e18eb1cb37dca3c8484434221f17bd93c6194e08bfc82f0032fa07",
)

RULES_DOCKER = struct(
    commit = "47cd9f9821a24df5df227e5c2876dd11dc1171bf",
    sha256 = "4a9a86f1a7137e96854f08eb1107b886e95c2ea55b3831b3472eaf23f212ce0f",
)

LAYER_DEFINITIONS = struct(
    commit = "71c810c91fa7f515680c52c234f52e3b1872ad56",
    sha256 = "ce7d259060687c49253a882af70dee66a0938fc9adcf10e2988024061623b5dd",
)
